apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: orderservice
spec:
  type: NodePort
  ports:
  - port: 8080
  targetPort: 8080
  nodePort: 30007
  selector:
    app: orderservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - name: orderservice
        image: https://hub.docker.com/repository/docker/fisnikz/orders-service
        ports:
        - containerPort: 8080
